### ISSUE TITLE
__dict__ instead of 'if' sentence in class __init__

### ISSUE THREAD

**Issue by isman7** [Eiyeron/telegram-bot-api#2]
Hey, I am reading the code, and first impressions are good. I will try to help during the vacations. I'm finishing now the course and I have lot of work. 

Only, comment an idea. As you can see in my lib https://github.com/isman7/tgbot/, you can try to use the **dict** method to pass attributes to a certain object in the **init** to avoid all this "if" in **models.py**. 

If I am able to have an hour during this week I will prove to port and test. 

See you.

**Comment by Eiyeron** [comment]
Yeah, I learned the trick a bit after coding so I (or you, if you want to do it) should switch over this command. It should make the code cleaner. THanks for noticing!

Edit : Actually, I learned about copying a dict's key or a placeholder if the dict doesn't have the key but as here I'm not adding the element to the dict if it's not given, I'm still searching how I could apply your method.

**Comment by isman7** [comment]
I will start merging my code into the fork I've created. And try to run it. 

About the Edit, I'm confused. Did you mean that you need to create all the posible attributes, for example in Message class, or not?

**Comment by Eiyeron** [comment]
I'm not creating the objects when they're not stored in the update, hence the conditions.

**Comment by Eiyeron** [comment]
It seems to work, sorry for the wait. YOur branch is merged. THanks for your work!
